{
 "title": "Air_Quality_Dashboard",
 "tags": [
  "IoT",
  "AirQuality",
  "API",
  "NodeExporter"
 ],
 "time": { "from": "2025-11-19T17:30:09.432Z", "to": "2025-11-19T17:40:09.432Z" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Ventilation Required",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ventilation_status" }
   ]
  },
  {
   "title": "Ventilation Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 0 },
   "targets": [
    { "expr": "ventilation_status", "legendFormat": "Ventilation" }
   ]
  },
  {
   "title": "Latest Ventilation Values",
   "type": "table",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 6 },
   "targets": [
    { "expr": "ventilation_status" }
   ]
  },
  {
   "title": "API Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler!~\"/metrics\"}[5m])",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "API Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=\"airquality-ml-api\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "API Container CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"airquality-ml-api\"}[5m])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}